try again

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -43,21 +43,21 @@ jobs:
 
       - name: Verify gmp build
         run: |
-            echo "#include <gmp.h>" | ${CXX} -E -lgmp -xc++ - >/dev/null 2>&1
-            if [ $? -ne 0 ]; then
-              echo "#include <gmp.h>" | ${CXX} -E -lgmp -xc++ -
-              echo "failed"
-              exit 1;
-            fi
+          echo "#include <gmp.h>" | ${CXX} -E -lgmp -xc++ - >/dev/null 2>&1
+          if [ $? -ne 0 ]; then
+            echo "#include <gmp.h>" | ${CXX} -E -lgmp -xc++ -
+            echo "failed"
+            exit 1;
+          fi
 
-        - name: Verify gmpxx build
-          run: |
-            echo "#include <gmpxx.h>" | ${CXX} -E -lgmpxx -xc++ - >/dev/null 2>&1
-            if [ $? -ne 0 ]; then
-              echo "#include <gmpxx.h>" | ${CXX} -E -lgmpxx -xc++ -
-              echo "failed"
-              exit 1;
-            fi
+      - name: Verify gmpxx build
+        run: |
+          echo "#include <gmpxx.h>" | ${CXX} -E -lgmpxx -xc++ - >/dev/null 2>&1
+          if [ $? -ne 0 ]; then
+            echo "#include <gmpxx.h>" | ${CXX} -E -lgmpxx -xc++ -
+            echo "failed"
+            exit 1;
+          fi
 
       - name: Collect
         run: mkdir deploy && cp -p build/*-darwin*.tar.gz deploy/
