more debug

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -41,9 +41,18 @@ jobs:
       - name: Build R dependencies
         run: make -C build gmp
 
-      - name: Verify succesful build
+      - name: Verify gmp build
         run: |
+            echo "#include <gmp.h>" | ${CXX} -E -lgmp -xc++
             echo "#include <gmp.h>" | ${CXX} -E -lgmp -xc++ - >/dev/null 2>&1
+            if [ $? -ne 0 ]; then
+              echo "failed"
+              exit 1;
+            fi
+
+        - name: Verify gmpxx build
+        run: |
+            echo "#include <gmpxx.h>" | ${CXX} -E -lgmpxx -xc++ - >/dev/null 2>&1
             if [ $? -ne 0 ]; then
               echo "failed"
               exit 1;
